### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by lumiscosity** [lumiscosity/Editor#2]
The primary motivation of this fork is making an editor suitable for the average developer's experience with Collective Unconscious; doing so would allow us to officially move to .ogg files to decrease the filesize of subsequent dev builds, among other benefits. If this benchmark is reached and I'm still willing to work on the project, I'll most likely officially rebrand it as a separate entity from the upstream Editor, similar to projects like Prism Launcher.

This fork (henceforth referred to by its codename, Toucan) has the explicit goal of being a somewhat familiar replacement for the vanilla editor while ironing out some frustrations with it. It also implements EasyRPG features (and might implement patch features down the line), but as an independent project it has no bearing on the development and capabilities of EasyRPG; Toucan is developed for EasyRPG, but EasyRPG isn't developed for Toucan.

I grant explicit permission to EasyRPG's developers to backport any improvements from this fork to the upstream Editor.

### Expected features

- [X] Qt6 port
- [X] Proper panorama support
- [X] Charset picker for events
- [x] Database terrain and tileset editing
- [x] Music playback
- [ ] Command picker
- [ ] Move route menu

## Commands to implement
- [x] Comment
- [ ] String/variable operations
- [ ] Conditional branch
- [ ] Transfer player
- [ ] Call event
- [ ] Loop (no data; only placement code required)
- [ ] Play sound/music
- [ ] Fade out BGM
- [ ] Show Battle Animation
- [ ] Change event location
- [ ] Show/move/erase picture
- [ ] Show/hide screen
- [ ] Toggle player visibility
- [ ] Pan screen
- [ ] Flash event
- [ ] Wait
- [ ] Set move route
